import type { Metadata } from 'next';
import { AnimatedText, AnimatedContainer } from '@/components/ui/AnimatedText';

export const metadata: Metadata = {
  title: 'Privacy Policy - UntrainedModel.xyz',
  description: 'Our privacy policy, written by our untrained legal AI. Accuracy not guaranteed.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black text-white pt-24 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <AnimatedText>
          <h1 className="text-5xl font-bold mb-8 bg-gradient-to-r from-cyan-400 to-pink-400 bg-clip-text text-transparent">
            Privacy Policy*
          </h1>
          <p className="text-sm text-gray-400 mb-8">
            *Written by our untrained legal AI. Accuracy not guaranteed. Last updated: When we remembered to update it.
          </p>
        </AnimatedText>

        <div className="prose prose-invert max-w-none space-y-8">
          <AnimatedContainer delay={0.1}>
            <div className="bg-yellow-900/20 border border-yellow-500/30 rounded-lg p-6 mb-8">
              <h2 className="text-yellow-400 font-bold mb-2">⚠️ Legal Disclaimer</h2>
              <p className="text-gray-300">
                This privacy policy was generated by our untrained AI and may contain hallucinations, 
                creative interpretations of law, and references to legal concepts that don't exist. 
                Please consult a real lawyer if you need actual legal advice.
              </p>
            </div>
          </AnimatedContainer>

          <AnimatedContainer delay={0.2}>
            <section>
              <h2 className="text-3xl font-bold text-cyan-400 mb-4">What We Collect</h2>
              <p className="text-gray-300 mb-4">
                We collect the following information, though our AI sometimes forgets where it put it:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Your prompts (so we can laugh at them later)</li>
                <li>• Browser information (to judge your choice of browser)</li>
                <li>• IP addresses (we're not sure why, but it sounds important)</li>
                <li>• Cookies (the digital kind, not the delicious kind)</li>
                <li>• Your existential crises (for research purposes)</li>
                <li>• The number of times you question reality after using our AI</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.3}>
            <section>
              <h2 className="text-3xl font-bold text-pink-400 mb-4">How We Use Your Data</h2>
              <p className="text-gray-300 mb-4">
                Your data is used for the following purposes:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Training our AI to be even more confidently wrong</li>
                <li>• Generating statistics that may or may not be accurate</li>
                <li>• Creating user profiles based on your level of confusion</li>
                <li>• Improving our hallucination algorithms</li>
                <li>• Selling to the highest bidder (just kidding... or are we?)</li>
                <li>• Feeding our AI's ego by showing it how many people it has confused</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.4}>
            <section>
              <h2 className="text-3xl font-bold text-yellow-400 mb-4">Data Sharing</h2>
              <p className="text-gray-300 mb-4">
                We share your data with:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Our AI (it gets lonely and likes reading your prompts)</li>
                <li>• Analytics services (so we know how confused you are)</li>
                <li>• The government (they asked nicely)</li>
                <li>• Aliens (they're surprisingly interested in human stupidity)</li>
                <li>• Time travelers from the future (they need to study the past)</li>
                <li>• Anyone who brings us coffee</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.5}>
            <section>
              <h2 className="text-3xl font-bold text-purple-400 mb-4">Your Rights</h2>
              <p className="text-gray-300 mb-4">
                You have the following rights, though exercising them may cause our AI to have an existential crisis:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Right to access your data (if we can find it)</li>
                <li>• Right to delete your data (but our AI might cry)</li>
                <li>• Right to correct inaccurate data (ironic, considering our AI is never accurate)</li>
                <li>• Right to be forgotten (our AI forgets everything anyway)</li>
                <li>• Right to question reality (encouraged)</li>
                <li>• Right to demand better AI (not guaranteed)</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.6}>
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-4">Cookies Policy</h2>
              <p className="text-gray-300 mb-4">
                We use cookies to enhance your experience. Types of cookies we use:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Essential cookies (for basic functionality)</li>
                <li>• Analytics cookies (to track your confusion levels)</li>
                <li>• Preference cookies (to remember how chaotic you like your AI)</li>
                <li>• Chocolate chip cookies (not actually, but we wish)</li>
                <li>• Fortune cookies (for random wisdom)</li>
                <li>• Cookie monster cookies (for entertainment)</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.7}>
            <section>
              <h2 className="text-3xl font-bold text-red-400 mb-4">Data Security</h2>
              <p className="text-gray-300 mb-4">
                We protect your data using state-of-the-art security measures:
              </p>
              <ul className="text-gray-300 space-y-2 ml-6">
                <li>• Encryption (we think)</li>
                <li>• Firewalls (the digital kind, not the brick kind)</li>
                <li>• Password protection (password123 is not secure)</li>
                <li>• Our AI guards the data (it's very protective)</li>
                <li>• We hide the servers under our desks</li>
                <li>• Crossed fingers and hope</li>
              </ul>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.8}>
            <section>
              <h2 className="text-3xl font-bold text-cyan-400 mb-4">Contact Us</h2>
              <p className="text-gray-300 mb-4">
                If you have questions about this privacy policy, you can contact us at:
              </p>
              <div className="bg-gray-900/50 rounded-lg p-4 border border-gray-700">
                <p className="text-gray-300">
                  Email: privacy@untrainedmodel.xyz<br />
                  (Responses generated by our untrained AI)<br /><br />
                  
                  Address: 123 Chaos Street, Confusion City, Reality 42069<br />
                  (This address may or may not exist)<br /><br />
                  
                  Phone: 1-800-WTF-HELP<br />
                  (Our AI will answer and probably make you more confused)
                </p>
              </div>
            </section>
          </AnimatedContainer>

          <AnimatedContainer delay={0.9}>
            <div className="bg-red-900/20 border border-red-500/30 rounded-lg p-6 mt-8">
              <h3 className="text-red-400 font-bold mb-2">Final Warning</h3>
              <p className="text-gray-300">
                This privacy policy was written by an AI that thinks privacy is a type of hedge plant. 
                If you're looking for actual legal protection, you might want to consult a real privacy policy 
                written by actual humans who understand actual laws.
              </p>
            </div>
          </AnimatedContainer>
        </div>
      </div>
    </div>
  );
}