import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Brain, Zap, Skull, Users, Star, ChevronRight, Bug, Cpu, AlertTriangle } from 'lucide-react';

const Home = () => {
  const [currentTagline, setCurrentTagline] = useState(0);
  const [isGlitching, setIsGlitching] = useState(false);

  const taglines = [
    "Where dumb AI meets brilliant chaos",
    "The AI that forgot to train",
    "Just vibes. No accuracy",
    "LLM? More like LOLM",
    "Think like a billion-dollar startup. Build like a garage hacker"
  ];

  const features = [
    {
      icon: <Brain className="w-8 h-8" />,
      title: "Untrained Models",
      description: "Our AI has 2 neurons left and they're fighting each other. Perfect for creative chaos.",
      status: "BROKEN ✓"
    },
    {
      icon: <Bug className="w-8 h-8" />,
      title: "Guaranteed Bugs",
      description: "Why fix bugs when you can call them features? Our AI hallucinates professionally.",
      status: "CHAOTIC ✓"
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: "Random AF",
      description: "Predictable is boring. Our responses are generated by a magic 8-ball connected to GPT.",
      status: "RANDOM ✓"
    },
    {
      icon: <Skull className="w-8 h-8" />,
      title: "Anti-Corporate",
      description: "No suits, no buzzwords, no 'synergy'. Just pure, unfiltered AI rebellion.",
      status: "REBEL ✓"
    }
  ];

  const testimonials = [
    {
      name: "Anonymous Hacker",
      role: "Basement Dweller",
      content: "This AI told me to invest in Dogecoin. I did. Now I live in a cardboard box. 10/10 would recommend.",
      rating: 5,
      avatar: "🤖"
    },
    {
      name: "Confused Developer",
      role: "Stack Overflow Refugee",
      content: "Asked it to debug my code. It suggested I become a farmer instead. Honestly, best career advice ever.",
      rating: 5,
      avatar: "👨‍💻"
    },
    {
      name: "Startup Bro",
      role: "Failed Entrepreneur",
      content: "Used this for my pitch deck. VCs laughed so hard they forgot to reject me. Still no funding tho.",
      rating: 4,
      avatar: "🤵"
    }
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTagline((prev) => (prev + 1) % taglines.length);
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const glitchInterval = setInterval(() => {
      setIsGlitching(true);
      setTimeout(() => setIsGlitching(false), 200);
    }, 5000);

    return () => clearInterval(glitchInterval);
  }, []);

  return (
    <div className="pt-20">
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        {/* Animated background chaos */}
        <div className="absolute inset-0">
          <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-pink-500/10 rounded-full blur-3xl chaos-float"></div>
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl chaos-float" style={{animationDelay: '2s'}}></div>
          <div className="absolute top-1/2 left-1/2 w-32 h-32 bg-yellow-500/10 rounded-full blur-2xl chaos-float" style={{animationDelay: '4s'}}></div>
        </div>

        <div className="container mx-auto px-6 text-center relative z-10">
          <div className="mb-8">
            <span className="neon-pink mono text-sm">SYSTEM STATUS: COMPLETELY BROKEN</span>
          </div>
          
          <h1 className={`text-5xl md:text-8xl font-bold text-white mb-6 leading-tight mono ${isGlitching ? 'glitch-text' : ''}`}>
            Meet the
            <span className="block neon-pink glitch-text">DUMBEST AI</span>
            <span className="block text-3xl md:text-5xl neon-cyan">on the internet</span>
          </h1>
          
          <div className="h-16 mb-8">
            <p className="text-xl md:text-2xl text-gray-300 mono typing-effect">
              {taglines[currentTagline]}
            </p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
            <Link
              to="/playground"
              className="chaos-btn text-lg mono flex items-center space-x-2"
            >
              <span>TRY PLAYGROUND</span>
              <ArrowRight size={20} />
            </Link>
            
            <Link
              to="/hallucinations"
              className="border-2 border-pink-500 text-pink-400 px-8 py-4 font-semibold hover:bg-pink-500/20 transition-all duration-300 flex items-center space-x-2 mono"
            >
              <span>SEE FAILURES</span>
              <ChevronRight size={20} />
            </Link>
          </div>

          <div className="terminal max-w-2xl mx-auto">
            <div className="mono text-green-400 text-left">
              <div className="mb-2">$ ./untrained_model --status</div>
              <div className="text-yellow-400 mb-1">WARNING: AI not found. Using random number generator instead.</div>
              <div className="text-pink-400 mb-1">ERROR: Logic.exe has stopped working</div>
              <div className="text-cyan-400 mb-1">INFO: Chaos mode activated successfully</div>
              <div className="text-green-400">READY: Let's break some stuff! 🔥</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-900/50">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-6xl font-bold text-white mb-6 mono">
              Why We're <span className="neon-pink glitch-text">DIFFERENT</span>
            </h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto mono">
              We're not just another AI company. We're the AI company that gave up trying to be smart.
            </p>
          </div>

          <div className="broken-grid max-w-6xl mx-auto">
            {features.map((feature, index) => (
              <div
                key={index}
                className="chaos-card hover:scale-105 transition-transform duration-300"
              >
                <div className="text-pink-400 mb-4 flicker">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold text-white mb-4 mono">{feature.title}</h3>
                <p className="text-gray-300 leading-relaxed mb-4">{feature.description}</p>
                <div className="success-text mono text-sm">{feature.status}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">
            <div className="space-y-2">
              <div className="text-4xl md:text-5xl font-bold neon-pink mono glitch">404</div>
              <div className="text-gray-300 mono">Models Trained</div>
              <div className="text-xs text-gray-500 mono">(we lost count)</div>
            </div>
            <div className="space-y-2">
              <div className="text-4xl md:text-5xl font-bold neon-cyan mono">0.1%</div>
              <div className="text-gray-300 mono">Accuracy Rate</div>
              <div className="text-xs text-gray-500 mono">(surprisingly high)</div>
            </div>
            <div className="space-y-2">
              <div className="text-4xl md:text-5xl font-bold neon-yellow mono">∞</div>
              <div className="text-gray-300 mono">Bugs Created</div>
              <div className="text-xs text-gray-500 mono">(it's a feature)</div>
            </div>
            <div className="space-y-2">
              <div className="text-4xl md:text-5xl font-bold neon-green mono">24/7</div>
              <div className="text-gray-300 mono">Chaos Support</div>
              <div className="text-xs text-gray-500 mono">(we never sleep)</div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-gray-900/50">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-6xl font-bold text-white mb-6 mono">
              What Our <span className="neon-cyan">VICTIMS</span> Say
            </h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto mono">
              Real testimonials from real people who made questionable life choices.
            </p>
          </div>

          <div className="broken-grid max-w-6xl mx-auto">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                className="chaos-card"
              >
                <div className="flex mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-yellow-400 fill-current flicker" />
                  ))}
                </div>
                <p className="text-gray-300 mb-6 leading-relaxed mono">"{testimonial.content}"</p>
                <div className="flex items-center space-x-3">
                  <div className="text-2xl">{testimonial.avatar}</div>
                  <div>
                    <div className="font-semibold text-white mono">{testimonial.name}</div>
                    <div className="text-pink-400 text-sm mono">{testimonial.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Warning Section */}
      <section className="py-20">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <div className="chaos-card border-2 border-red-500 bg-red-500/10">
              <div className="flex items-center space-x-4 mb-6">
                <AlertTriangle className="w-12 h-12 text-red-500 flicker" />
                <div>
                  <h2 className="text-3xl font-bold text-red-400 mono">⚠️ DISCLAIMER ⚠️</h2>
                  <p className="text-red-300 mono">Please read before proceeding</p>
                </div>
              </div>
              
              <div className="space-y-4 text-gray-300 mono">
                <p>• This AI is intentionally broken and will give you terrible advice</p>
                <p>• Do not use for medical, legal, or financial decisions (or do, we're not your mom)</p>
                <p>• Side effects may include: confusion, laughter, existential crisis</p>
                <p>• We are not responsible for any life choices you make based on our AI's suggestions</p>
                <p>• Seriously, it's just for fun. Don't take it seriously.</p>
              </div>
              
              <div className="mt-8 text-center">
                <Link
                  to="/playground"
                  className="chaos-btn text-lg mono"
                >
                  I UNDERSTAND THE RISKS, LET'S GO!
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-900/50">
        <div className="container mx-auto px-6 text-center">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-4xl md:text-6xl font-bold text-white mb-6 mono glitch-text">
              Ready to Break Things?
            </h2>
            <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto mono">
              Join the chaos. Embrace the bugs. Let's build something beautifully broken together.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/playground"
                className="chaos-btn text-lg mono"
              >
                START BREAKING STUFF
              </Link>
              <Link
                to="/train"
                className="border-2 border-cyan-500 text-cyan-400 px-8 py-4 font-semibold hover:bg-cyan-500/20 transition-all duration-300 mono"
              >
                TRAIN YOUR OWN CHAOS
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;